# Generated by Django 3.0.3 on 2020-09-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Topico')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Webpage')),
            ],
        ),
    ]
